package: 2factor_auth
version: '1.0.0-beta1'
author: 'Markus Staab'

page:
    title: 'dummy'
    hidden: true

pages:
    setup:
        title: '2 Faktor setup'
        hasNavigation: false
        path: pages/setup.php
    login:
        title: '2 Faktor login'
        hasNavigation: false
        path: pages/login.php

requires:
    php:
        version: '^7.1'
    redaxo: ^5.7.0-beta1