package: 2factor_auth
version: '2.0.4-dev'
author: 'Markus Staab'

page:
    title: 'translate:2factor_auth'
    icon: rex-icon fa-lock
    subpages:
        setup:
            title: 'translate:setup'
        docs:
            title: translate:help
            subPath: README.md

pages:
    2factor_auth_verify:
        title: 'translate:OTP-Verifizierung'
        hasNavigation: false
        main: true
        hidden: true
        path: pages/verify.php

console_commands:
    2factor_auth:enforce: rex_command_2factor_auth_enforce
    2factor_auth:user: rex_command_2factor_auth_user

requires:
    php:
        version: '>=7.2'
    redaxo: ^5.7.0

load: early
