package: 2factor_auth
version: '2.0.0-dev'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/2factor_auth

pages:
    2factor_auth_setup:
        title: '2 Faktor Setup'
        main: true
        icon: rex-icon rex-icon-install
        path: pages/setup.php
    2factor_auth_verify:
        title: '2 Faktor Verifizierung'
        hasNavigation: false
        main: true
        hidden: true
        path: pages/verify.php

requires:
    php:
        version: '>=7.1'
    redaxo: ^5.7.0

default_config:
    image: false
    image_url: https://raw.githubusercontent.com/FriendsOfREDAXO/friendsofredaxo.github.io/assets/v2/FOR-avatar-01.png

load: early
