package: 2factor_auth
version: '1.0.0-beta1'
author: 'Markus Staab'

pages:
    2factor_auth_setup:
        title: '2 Faktor setup'
        hasNavigation: false
        main: true
        path: pages/setup.php
    2factor_auth_verify:
        title: '2 Faktor verify'
        hasNavigation: false
        main: true
        path: pages/verify.php

requires:
    php:
        version: '^7.1'
    redaxo: ^5.7.0-beta1

load: early