package: 2factor_auth
version: '2.0.0-dev'
author: 'Markus Staab'

page:
    title: '2FA'
    subpages:
        setup:
            title: 'Setup'
        docs:
            title: Help
            subPath: README.md

pages:
    2factor_auth_verify:
        title: 'OTP-Verifizierung'
        hasNavigation: false
        main: true
        hidden: true
        path: pages/verify.php
requires:
    php:
        version: '>=7.2'
    redaxo: ^5.7.0

load: early
