package: 2factor_auth
version: '1.0.0'
author: 'Markus Staab'

pages:
    2factor_auth_setup:
        title: '2 Faktor Setup'
        main: true
        icon: rex-icon rex-icon-install
        path: pages/setup.php
    2factor_auth_verify:
        title: '2 Faktor Verifizierung'
        hasNavigation: false
        main: true
        hidden: true
        path: pages/verify.php
    2factor_auth_help: 
        title: Hilfe
        SubPath: README.md
        itemclass: pull-right 
        
requires:
    php:
        version: '^7.1'
    redaxo: ^5.7.0

load: early
