package: 2factor_auth
version: '2.2'
author: 'Markus Staab, Jan Kristinus'

page:
    title: 'translate:2factor_auth'
    icon: rex-icon fa-lock
    subpages:
        setup:
            title: 'translate:2factor_auth_private_setup'
        docs:
            title: translate:readme
            subPath: README.md
            icon: rex-icon fa-info-circle
            itemclass: pull-right
        users:
            title: translate:users
            perm: admin[]
            itemclass: pull-right
        settings:
            title: 'translate:2factor_auth_settings'
            perm: admin[]
            itemclass: pull-right

pages:
    2factor_auth_verify:
        title: 'translate:OTP-Verifizierung'
        hasNavigation: false
        main: true
        hidden: true
        path: pages/verify.php

console_commands:
    2factor_auth:enforce: rex_command_2factor_auth_enforce
    2factor_auth:user: rex_command_2factor_auth_user
    2factor_auth:status: rex_command_2factor_auth_status

requires:
    php:
        version: '>=8.1'
    redaxo: ^5.14.0

load: early
