package: 2factor_auth
version: '1.0.0'
author: 'Markus Staab'

pages:
    2factor_setup:
        title: '2FA/OTP'
        block: system        
        main: true
        icon: rex-icon rex-icon-install
        path: pages/setup.php

    2factor_auth_verify:
        title: '2FA/OTP'
        block: system
        hasNavigation: false
        main: true
        hidden: true
        path: pages/verify.php
        
    docs:
        title: Docs
        block: system
        subPath: README.md
        icon: rex-icon fa-info-circle
        itemclass: pull-right
        perm: admin

requires:
    php:
        version: '^7.1'
    redaxo: ^5.7.0

load: early
