package: 2factor_auth
version: '2.0.3'
author: 'Markus Staab'

page:
    title: '2 Faktor Login'
    icon: rex-icon fa-lock
    subpages:
        setup:
            title: 'Setup'
        docs:
            title: Help
            subPath: README.md

pages:
    2factor_auth_verify:
        title: 'OTP-Verifizierung'
        hasNavigation: false
        main: true
        hidden: true
        path: pages/verify.php

console_commands:
    2factor_auth:enforce: rex_command_2factor_auth_enforce
    2factor_auth:user: rex_command_2factor_auth_user

requires:
    php:
        version: '>=7.2'
    redaxo: ^5.7.0

load: early
